language: php

php:
    - 7.1

## Update composer and run the appropriate composer command
before_script:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - travis_retry composer self-update
    - travis_retry composer global require "fxp/composer-asset-plugin:~1.3"
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
